### ISSUE TITLE
War files should be released in a durable maven repository

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/getting-started-java#118]
To aid in automated testing of gcloud, the war files in this git repository should be versioned, and published in a durable maven repository somewhere.

This doesn't mean maven central, just a maven repository somewhere accessible.

Release builds are a definite, and SNAPSHOT builds could be optional (and should be in a separate snapshots maven repository)

**Comment by lesv** [comment]
Explain?

**Comment by joakime** [comment]
Ignore this issue, this project will not be used for automated testing of gcloud.
