### ISSUE TITLE
Bookshelf- maven doesnt start

### ISSUE THREAD

**Issue by dilrajgithub** [GoogleCloudPlatform/getting-started-java#133]
Is anyone getting an error while starting the local web server?  This is what I am getting-

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.078 s
[INFO] Finished at: 2016-10-11T16:40:25-04:00
[INFO] Final Memory: 6M/150M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "local" could not be activated because it does not exist.
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\Program Files (x86)\Google\Cloud SDK\getting-started-java\bookshelf). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by lesv** [comment]
Working on it -- the docs are incorrect.  (The sample was changed, I need to fix the docs, the readme's should be correct)

**Comment by lesv** [comment]
#151 should fix this, though we still need to update the public docs.
