### ISSUE TITLE
springboot - com.google.appengine:gcloud-maven-plugin:2.0.9.120.v20160803:dep loy failed. NullPointerException 

### ISSUE THREAD

**Issue by kamilwlf** [GoogleCloudPlatform/getting-started-java#135]
I run:

> mvn gcloud:deploy

result:

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 13.295 s
> [INFO] Finished at: 2016-10-12T16:54:34+02:00
> [INFO] Final Memory: 24M/244M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.google.appengine:gcloud-maven-plugin:2.0.9.120.v20160803:deploy (default-cli) on pr
> oject springappengine4: Execution default-cli of goal com.google.appengine:gcloud-maven-plugin:2.0.9.120.v20160803:dep
> loy failed. NullPointerException -> [Help 1]

FYI:

> mvn spring-boot:run

 works

**Comment by lesv** [comment]
Working on it

**Comment by kamilwlf** [comment]
For gradle it also does not work
