### ISSUE TITLE
Using Firebase and App Engine Standard Environment in a Spring Boot app

### ISSUE THREAD

**Issue by kamilwlf** [GoogleCloudPlatform/getting-started-java#139]
Can I integrate sprinng app on GAE with Firebase?
I try make use of:
https://cloud.google.com/solutions/mobile/firebase-app-engine-android-studio

but during deployment I got error:

> Deploying 'Maven build: springAppEngine4'...
> Created temporary staging directory: C:\Users\Kamil\AppData\Local\Temp\gae-staging-fir-33cf6
> You are about to deploy the following services:
> - fir-33cf6/default/20161013t100429 (from [C:\Users\Kamil\AppData\Local\Temp\gae-staging-fir-33cf6\app.yaml])
>    Deployed URL: [https://xxxx.appspot.com](add --promote if you also want to make this service available from
>    [https://fir-33cf6.appspot.com])
> 
> If this is your first deployment, this may take a while...
> 
> If this is your first deployment, this may take a while...failed.
> WARNING: We couldn't validate that your project is ready to deploy to App Engine Flexible Environment. If deployment fails, please try again.
> Beginning deployment of service [default]...
> WARNING: Deployment of App Engine Flexible Environment apps is currently in Beta
> Building and pushing image for service [default]
> ERROR: (gcloud.app.deploy) Project [fir-33cf6] not found.
> Failed to deploy 'Maven build: springAppEngine4': Deployment failed with exit code: 1
> Please make sure that you are using the latest version of the Google Cloud SDK.
> Run ''gcloud components update'' to update the SDK. (See: https://cloud.google.com/sdk/gcloud/reference/components/update.)

Is it possible to integrate firebase and Spring Boot app on GAE?

> Download the JSON key file for the service account and save it in the src/main/webapp/WEB-INF/ directory of the servlet component. The filename will be in the form [FIREBASE_PROJECT_ID]-[UNIQUE_ID].json

Where should I save JSON key file for Spring?

**Comment by lesv** [comment]
Springboot doesn't work w/ GAE Standard currently.
