### ISSUE TITLE
Intelij plugin deploy to App engine does not work with .jar project

### ISSUE THREAD

**Issue by kamilwlf** [GoogleCloudPlatform/getting-started-java#140]
I try to deploy app spring boot app:
settings: Filesystem **Jar**
Gradle

In plugin I see error"Invalid Data: Browe to a Jar or War file":

![screenshot - 2016-10-13 10_52_34](https://cloud.githubusercontent.com/assets/7765963/19342718/44740004-9133-11e6-8f00-cc0adf90939a.jpg)

With Jar it works

**Comment by lesv** [comment]
I think this works to GAE Flex now.  If this is still an issue, please reopen on the intellij plugin Github repo.
