### ISSUE TITLE
Bookshelf README is missing required environment variables

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/getting-started-java#15]
When I try to run Bookshelf with `mvn jetty:run` I get a NullPointerException.

![image](https://cloud.githubusercontent.com/assets/247555/12736183/ef32d686-c902-11e5-9851-bfad1873cfda.png)

I believe that this is because [System.getenv](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#getenv--) returns null when the environment variable is not defined. This throws a NullPointerException when it [gets to the switch](https://github.com/GoogleCloudPlatform/getting-started-java/blob/255500f59a83f54fa17604c1bc3095a9a2eeff58/bookshelf/src/main/java/com/example/managedvms/gettingstartedjava/basicactions/ListBookServlet.java#L55). It does not hit the default clause.

I see that there are other calls to `System.getenv` in the repo that would need updating, too.

**Comment by tswast** [comment]
CC @lesv @shun-fan

**Comment by lesv** [comment]
Tim are you going to fix this?  Or should it be @shun-fan ??

**Comment by tswast** [comment]
I'm okay to fix it. I need to figure it out how to run Bookshelf locally, anyway, for a Compute Engine sample.

**Comment by YnR** [comment]
I wanted to use the sample as well, and looked at the app.yaml file for deployment. It has dummy env variables, and I don't know what to put instead of what's there:
```
# [START env_variables]
env_variables:
STORAGETYPE: YOUR_DATABASE-CHOICE
...
# [END env_variables]
```

Maybe you could do it like the Apache config file, have comments showing the acceptable options or examples?

**Comment by shun-fan** [comment]
So if you run it locally you have to set the environment variables on your local environment. It's not going to read it from the app.yaml file.

**Comment by YnR** [comment]
Do I have to set those if I run remotely?

**Comment by YnR** [comment]
So if I follow the instructions in the Readme file (mvn jetty:run) I get:

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building bookshelf 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> jetty-maven-plugin:9.3.7.v20160115:run (default-cli) > test-compile @ bookshelf >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ bookshelf ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\yannr\workspace\getting-started-java\bookshelf\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ bookshelf ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 15 source files to C:\Users\yannr\workspace\getting-started-java\bookshelf\target\bookshelf-1.0-SNAPSHOT\WEB-INF\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.004 s
[INFO] Finished at: 2016-02-10T13:39:07-08:00
[INFO] Final Memory: 12M/115M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project bookshelf: Fatal error com
: invalid target release: 1.8 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by shun-fan** [comment]
what java version are you using? 
if you run remotely, the environment variables within the app.yaml will be used.

**Comment by YnR** [comment]
So I verified that this does not work locally on Mac or Windows. On either, I have to set the ENV variables manually.

**Comment by lesv** [comment]
Totally - we are are switching to using web.xml -- README will be update before Monday.

**Comment by lesv** [comment]
Updated README.
