### ISSUE TITLE
No pom.xml in getting-started-java/bookshelf directory

### ISSUE THREAD

**Issue by subhay389** [GoogleCloudPlatform/getting-started-java#150]
In the documentation, it asks to edit pom.xml located in the bookshelf direct. However, this file is not present. It disables me from deploying

**Comment by lesv** [comment]
What's missing from the documentation is to go into the directory for each section
bookshelf/
  2-structured-data/
  3-binary-data/
  4-auth/

etc.

Each chapter has a directory -- Hope to get this fixed this week.

**Comment by lesv** [comment]
@steveperry-53 FYI

**Comment by lesv** [comment]
Should be better once #151 releases
