### ISSUE TITLE
Link in README.md goes to 404

### ISSUE THREAD

**Issue by bendory** [GoogleCloudPlatform/getting-started-java#174]
On https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/bookshelf/optional-container-engine, the README.md says:

Please refer to the Tutorial for instructions on how to deploy this sample.

The word "Tutorial" links to https://cloud.google.com/java/tutorials/bookshelf-on-container-engine which does not exist.

**Comment by lesv** [comment]
It's been fixed.
