### ISSUE TITLE
Update build.gradle to use httpPort

### ISSUE THREAD

**Issue by ericranstrom** [GoogleCloudPlatform/getting-started-java#192]
gretty `port` has been [deprecated](http://akhikhl.github.io/gretty-doc/Gretty-configuration.html) and `httpPort` should be used instead.  Without this change, I see the error `Could not set unknown property 'port' for object of type org.akhikhl.gretty.GrettyExtension.` when I run `./gradlew jettyRun`

**Comment by averikitsch** [comment]
This has been updated for all samples
