### ISSUE TITLE
SpringBoot starter broken...

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/getting-started-java#228]
I disabled testing and building of Spring-Boot getting started as testing has broken.  I'll reenable when I return.

**Comment by chanseokoh** [comment]
Seems like the broken tests have been fixed by #303. Probably you can enable it now.

`pom.xml`
```xml
        <module>helloworld-jsp</module>
        <module>helloworld-servlet</module>
<!--
        <module>helloworld-springboot</module>
 -->
    </modules>
```
