### ISSUE TITLE
Deployed springboot-appengine-standard and got "Error: Not Found" in the browser

### ISSUE THREAD

**Issue by tkob** [GoogleCloudPlatform/getting-started-java#259]
I'm trying appengine-standard-java8 applications.
As for `appengine-standard-java8/helloworld`, `mvn clean appengine:deploy` succeeds and I can see the app working in the browser.
I'm in trouble with `appengine-standard-java8/springboot-appengine-standard`:

 * `mvn clean appengine:deploy` succeeds,
 * but when I open the application in the browser, I get "Error: Not Found"

How can I investigate the cause?

**Comment by lesv** [comment]
Sorry for the delay.  I usually look in the logs for any clue to why it didn't startup properly.

**Comment by tkob** [comment]
Which logs? Stackdriver logging only tells me there are CreateVersion activities and requests which result in 404 (filtered by GAE application and all logs)

**Comment by lesv** [comment]
The default of StackDriver logging is to show request logs, I usually like to look at all of them, there should be some info about startup and maybe what is wrong.

**Comment by tkob** [comment]
I have succeeded in deployment. Probably Cloud SDK version matters.
Upgrading from 155.0.0 to 164.0.0 resolved the issue,

**Comment by iwag** [comment]
I was stuck with same problem for a couple of hours.  This issue gave me a great hint (I forgot to upgrade gcloud component)
In my case this error message appeared in the browser

```
There was an unexpected error (type=Internal Server Error, status=500). com.google.appengine.tools.development.ResponseRewriterFilter
```

Thanks @tkob

**Comment by blueneel05** [comment]
You did the update on local machine and then used mvn clean appengine:deploy or did gcloud components update on app engine ?
