### ISSUE TITLE
Getting error scanning file when running kotlin-spark-appengine-standard

### ISSUE THREAD

**Issue by VitaminPSG** [GoogleCloudPlatform/getting-started-java#261]
I'm running a trivial Hello World module from the repository. But it seems that jetty can't fin my servlet class when running  **mvn appengine:run**, what am I missing here?

> [INFO] GCLOUD: 2017-07-19 15:05:03.003:INFO::main: Logging initialized @533ms
[INFO] GCLOUD: Jul 19, 2017 2:05:03 PM com.google.appengine.tools.development.IsolatedAppClassLoader checkWorkingDirectory
[INFO] GCLOUD: WARNING: Your working directory, (/Users/bawl/Downloads/getting-started-java-master/appengine-standard-java8/kotlin-spark-appengine-standard) is not equal to your 
[INFO] GCLOUD: web application root (/Users/bawl/Downloads/getting-started-java-master/appengine-standard-java8/kotlin-spark-appengine-standard/target/kotlin-spark-appengine-standard-1.0-SNAPSHOT)
[INFO] GCLOUD: You will not be able to access files from your working directory on the production server.
[INFO] GCLOUD: 
[INFO] GCLOUD: 2017-07-19 15:05:03.342:INFO:oejs.Server:main: jetty-9.3.18.v20170406
[INFO] GCLOUD: 2017-07-19 15:05:04.965:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=1484ms
[INFO] GCLOUD: 2017-07-19 15:05:04.966:WARN:oejw.WebAppContext:main: Failed startup of context c.g.a.t.d.j.DevAppEngineWebAppContext@3c3d9b6b{/,file:///Users/bawl/Downloads/getting-started-java-master/appengine-standard-java8/kotlin-spark-appengine-standard/target/kotlin-spark-appengine-standard-1.0-SNAPSHOT/,UNAVAILABLE}{/Users/bawl/Downloads/getting-started-java-master/appengine-standard-java8/kotlin-spark-appengine-standard/target/kotlin-spark-appengine-standard-1.0-SNAPSHOT}
[INFO] GCLOUD: java.lang.RuntimeException: Error scanning entry module-info.class from jar file:///Users/bawl/Downloads/getting-started-java-master/appengine-standard-java8/kotlin-spark-appengine-standard/target/kotlin-spark-appengine-standard-1.0-SNAPSHOT/WEB-INF/lib/slf4j-api-1.8.0-alpha2.jar
[INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:906)
[INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
[INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
[INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
[INFO] GCLOUD: 	at java.lang.Thread.run(Thread.java:748)
[INFO] GCLOUD: Caused by: 
[INFO] GCLOUD: java.lang.IllegalArgumentException
[INFO] GCLOUD: 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
[INFO] GCLOUD: 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
[INFO] GCLOUD: 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
[INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:977)
[INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
[INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
[INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
[INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
[INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
[INFO] GCLOUD: 	at java.lang.Thread.run(Thread.java:748)
[INFO] GCLOUD: 2017-07-19 15:05:04.976:INFO:oejs.AbstractConnector:main: Started NetworkTrafficSelectChannelConnector@1190200a{HTTP/1.1,[http/1.1]}{localhost:8080}
[INFO] GCLOUD: 2017-07-19 15:05:04.991:INFO:oejs.Server:main: Started @2521ms
[INFO] GCLOUD: Jul 19, 2017 2:05:04 PM com.google.appengine.tools.development.AbstractModule startup
[INFO] GCLOUD: INFO: Module instance default is running at http://localhost:8080/
[INFO] GCLOUD: Jul 19, 2017 2:05:04 PM com.google.appengine.tools.development.AbstractModule startup
[INFO] GCLOUD: INFO: The admin console is running at http://localhost:8080/_ah/admin
[INFO] GCLOUD: Jul 19, 2017 3:05:04 PM com.google.appengine.tools.development.DevAppServerImpl doStart
[INFO] GCLOUD: INFO: Dev App Server is now running

**Comment by lesv** [comment]
It should be working now.
