### ISSUE TITLE
Gradle suppport for App Engine Standard Java8

### ISSUE THREAD

**Issue by captainjapeng** [GoogleCloudPlatform/getting-started-java#266]
Provide gradle files for

- [kotlin-appengine-standard](https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/kotlin-appengine-standard)
- [kotlin-spark-appengine-standard](https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/kotlin-spark-appengine-standard)
- [kotlin-springboot-appengine-standard](https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/kotlin-springboot-appengine-standard)
- [sparkjava-appengine-standard](https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/sparkjava-appengine-standard)
- [springboot-appengine-standard](https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/springboot-appengine-standard)

**Comment by captainjapeng** [comment]
Here's my attempt to convert **kotlin-springboot-appengine-standard**'s pom.xml

https://gist.github.com/captainjapeng/fbaf5cfb2f45994888c615ba276c1580

**Comment by notona** [comment]
you need this configuration
```
configurations.all {
    exclude group: 'org.slf4j', module: 'jul-to-slf4j'
}
```

and delete this line.
```
exclude group: "org.slf4j", module: "jul-to-slf4j"
```

**Comment by averikitsch** [comment]
At this time, we are unable to support this request.
