### ISSUE TITLE
app engine standard java 8 spring boot instructions need an extra step for spring devtools users

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/getting-started-java#294]
Devtools should be removed:
```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
		</dependency>
```
`mvn clean `needs to be run before a restart or the user will see:
```
 java.lang.IllegalArgumentException: Unable to find the main class to restart
	at org.springframework.util.Assert.notNull(Assert.java:134)
	at org.springframework.boot.devtools.restart.Restarter.doStart(Restarter.java:285)
 	at org.springframework.boot.devtools.restart.Restarter.start(Restarter.java:273)
```

**Comment by saturnism** [comment]
@lesv @jabubake

**Comment by jabubake** [comment]
@patflynn : sorry, I had n't noticed the fixes issues list in the PR that got merged. 
The issue you've opened needs to be addressed. The PR only fixed Flex hello world.

@patflynn : https://github.com/spring-projects/spring-boot/issues/7479 (not sure marking this as `optional` helps resolve this, but I'll look into this).

**Comment by averikitsch** [comment]
This has been removed
