### ISSUE TITLE
Misleading Javadoc in the Spring Boot sample

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/getting-started-java#300]
[The Javadoc of the Spring Boot sample](https://github.com/GoogleCloudPlatform/getting-started-java/blob/master/helloworld-springboot/src/main/java/com/example/java/gettingstarted/HelloworldApplication.java#L34
) says

> `App Engine health checking</a> requires responding with 200 to {@code /_ah/health}.`

However, that is not really true, according to the official doc: https://cloud.google.com/appengine/docs/flexible/python/how-instances-are-managed#health_checking

> You do not have to do anything special to implement health checking. If your app does not handle health checks, a HTTP 404 response is interpretated as a successful reply.

I think Spring Boot will return 404 by default (unconfimed), so maybe `@RequestMapping("/_ah/health")` is not necessary either.

**Comment by lesv** [comment]
@jabubake Don't know if you have cycles for this, if not assign back to me.  At one time, the /_ah/health was required - perhaps it's not now.
