### ISSUE TITLE
mvn didn't populate the pom properties in web.xml file in target causing error

### ISSUE THREAD

**Issue by winghong1234** [GoogleCloudPlatform/getting-started-java#302]
pom.xml has this 
winghong_wh1@winghong-prj-3:~/getting-started-java/bookshelf/6-gce$ grep -i datastore pom.xml
    <bookshelf.storageType>datastore</bookshelf.storageType>   

but after mvn clean jetty:run-exploded  -DprojectID=winghong-prj-3   -Dbookshelf.bucket=winghong-prj-3.appspot.com

The web.xml in target didn't seem to be populated by the pom.xml 's property, as shown below

 winghong_wh1@winghong-prj-3:~/getting-started-java/bookshelf/6-gce$ grep -i storagetype target/bookshelf-1.0-SNAPSHOT/WEB-INF/web.xml
        <param-name>bookshelf.storageType</param-name>
        <param-value>${bookshelf.storageType}</param-value>
winghong_wh1@winghong-prj-3:~/getting-started-java/bookshelf/6-gce$ 

winghong_wh1@winghong-prj-3:~/getting-started-java/bookshelf/6-gce$ 

And thus causing error 
java.lang.IllegalStateException: Invalid storage type. Check if bookshelf.storageType property is set.
        at com.example.getstarted.basicactions.ListBookServlet.init(ListBookServlet.java:70)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:637)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:421)

**Comment by jgmatu** [comment]
Same error.... I have solved the problem change the file in src web.xml setting datastore

**Comment by dashk** [comment]
Ran into the same issue, and what @jgmatu recommended fixed it.

Google's Getting Started with Java guide also missed the steps required to get the demo running. https://cloud.google.com/java/getting-started/using-forms (As of time of writing.)

In case the guide hasn't been updated, you'll need to do the following:
1. Follow https://github.com/GoogleCloudPlatform/getting-started-java/blob/master/bookshelf/README.md to get your bookshelf setup.
2. Edit `<getting-started-java>/bookshelf/2-structured-data/src/main/webapp/WEB-INF/web.xml`, replace `<param-value>${bookshelf.storageType}</param-value>` with `<param-value>datastore</param-value>`

**Comment by briandealwis** [comment]
The `getting-started-java/bookshelf/2-structured-data` example is referenced from the GCP [_Getting Started_](https://cloud.google.com/java/getting-started/using-forms) Java documentation and this issue makes GCP seem broken.

The root cause of the `bookshelf.storageType` problem is that these examples don't specify a version for  `maven-war-plugin` and so Maven is defaulting to 3.1.0.  But support for the `maven.war.filteringDeploymentDescriptors` property was removed as of 3.0 ([MWAR-376](https://issues.apache.org/jira/browse/MWAR-376)).

**Comment by lesv** [comment]
Couldn't agree more -- I've asked someone to look at this, if it's not done, I'll take it.
