### ISSUE TITLE
Getting timeout exception while connecting third party mongo db

### ISSUE THREAD

**Issue by arunrajgm** [GoogleCloudPlatform/getting-started-java#315]
Here i am connecting third party mongo db with direct uri not from http call. 
Everything works fine on local. 
After deployed my project to appengine i am not able to connect mongo db.
Getting mongotimeout exception.
I hope app engine block mongodb port 27017
If yes plz help me to resolve this issue.
If not what will be the problem here
I configured the mongo uri in application.yml file

spring:
  data:
    mongodb:
      uri: mongodb://userName:password@hostName:27017/dbName?ssl=true

Thanks

**Comment by arunrajgm** [comment]
@jabubake @lesv

**Comment by lesv** [comment]
GAE Standard or Flex?
Flex should work if you do this.  If not, tell me a bit more.  For GAE Standard, you are trying to go from GAE ==> GCP.  You need to open a public port.

**Comment by arunrajgm** [comment]
Hey @lesv 
I am refering this project 
[https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/springboot-appengine-standard](url)
I am deployed this on GAE standard
GAE flex and GCP both are having one year free limit.After that i need to pay some amount what i used that resource.
But GAE standard i always have some free quota(life time)
In my project i like to use springboot with maven and mongodb.
So i deployed my spring boot application with mongodb on GAE standard using this command 
"mvn appengine:deploy"
i hope it will deploy GAE standard becaz sofar i didnt enable billing on my project, so flex is not work.
So i am sure i am using GAE standard.
but i am facing mongotimeout exception on server, so i need to open port.
so i need to open port on GAE standard.
can you help me to how to open 27017 port?
or if any trick to using someother available port to act like 27017 i am not sure is this correct or not

Thanks

**Comment by arunrajgm** [comment]
@jabubake @lesv any solution for this?

**Comment by lesv** [comment]
@jabubake PTAL
@arunrajgm Sorry - I'm out for a few weeks more.

**Comment by jabubake** [comment]
For the use case, I would recommend referring to these resources
https://cloud.google.com/python/getting-started/deploy-mongodb

https://github.com/GoogleCloudPlatform/appengine-websocketchat-java
show cases how to create a firewall rule to open the port.

Let me know if that helps.

**Comment by jabubake** [comment]
I'm sorry, I just realized you are looking to use App engine standard, and I don't think there is an easy way to achieve this without using the Flex / Compute (VM) runtime.
