### ISSUE TITLE
All logs appear as INFO in stackdriver

### ISSUE THREAD

**Issue by mbyrne00** [GoogleCloudPlatform/getting-started-java#352]
Hi,

I've used the tips in `springboot-appengine-standard`. I had log statements for various levels, but everything comes across as `INFO` in stackdriver. In other projects where we have used `java.util` logging directly we managed to see the log level icon correctly in stackdriver, filter by level, etc.

As another note I can customise the log pattern to some extend in spring boot's standard property `logging.pattern.console` in springs application properties/yaml however I cannot get rid of the prefix that appears on the line: `[f~my-app-id/1.407102846225810748].<stdout>: ` that is part of the message. Once again on non spring apps using java util logger I did not see this. I tried various customisations of the util logging `logging.properties` too (e.g. https://github.com/GoogleCloudPlatform/appengine-pipelines/blob/master/java/example/war/WEB-INF/logging.properties) but these did not remove it. This pattern thing is not a massive deal, but would be nice to know how to remove it.

**Comment by averikitsch** [comment]
Using Logback is the preferred log formatter for Spring Boot. Checkout their [Logging docs](https://docs.spring.io/spring-boot/docs/1.5.x/reference/html/howto-logging.html) for more configuration info. Though focused on Cloud Run, [Java Logging on Cloud Run with Stackdriver](https://medium.com/google-cloud/java-logging-on-cloud-run-with-stackdriver-9786d6fdbe17) can provide more background.
