### ISSUE TITLE
parent POM inclusion errors

### ISSUE THREAD

**Issue by kmturley** [GoogleCloudPlatform/getting-started-java#354]
When following the guide at:
https://cloud.google.com/appengine/docs/standard/java/quickstart

The mvn appengine:run command fails with:

> The project com.example.appengine-j8:helloworld:1.0-SNAPSHOT (/usr/src/app/pom.xml) has 1 error. Non-resolvable parent POM for com.example.appengine-j8:helloworld:1.0-SNAPSHOT: Failure to find com.example:getting-started-java:pom:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 29, column 11 -> [Help 2]

This is because you have added a parent POM reference into the code:
```
  <parent>
    <artifactId>getting-started-java</artifactId>
    <groupId>com.example</groupId>
    <version>1.0.0</version>
    <relativePath>../..</relativePath>
  </parent>
```

Would suggest either removing the parent reference, ignoring it on build, or updating the documentation to inform users about how to comment out the dependency.

**Comment by dzlier-gcp** [comment]
This has since been updated to parent directly to shared-configuration.
