### ISSUE TITLE
web.xml IS required for helloworld for doGet to get called.

### ISSUE THREAD

**Issue by JohannBlake** [GoogleCloudPlatform/getting-started-java#358]
In the HelloWorld module, the following comment is present:

> // With @WebServlet annotation the webapp/WEB-INF/web.xml is no longer required.

This is false. The web.xml IS required. The web.xml doesn't specify the servlet in this case because the @WebServlet is used. BUT, if you do not provide a web.xml file, the doGet method will never get called. Please remove this comment.

See:
[https://stackoverflow.com/questions/11731377/servlet-returns-http-status-404-the-requested-resource-servlet-is-not-availa](https://stackoverflow.com/questions/11731377/servlet-returns-http-status-404-the-requested-resource-servlet-is-not-availa)

**Comment by lesv** [comment]
The comment should be changed.

The [Quickstart](https://webtide.com/jetty-9-quick-start/) process actually creates a web.xml for you, which it why it works for us.  However, someone forgot to include it in the latest `gcloud`, so it has broken a few things.

**Comment by parindholakia** [comment]
Also, :appengineStage task of gradle fails if we omit web.xml. Although local running of app works perfectly.But appengineDeploy task ultimately fails due to failure of  :appengineStage task.

@lesv I am using latest(Google Cloud SDK [187.0.0])  SDK version. still i am getting error while deploying war without web.xml

**Comment by patflynn** [comment]
@loosebazooka FYI

**Comment by lesv** [comment]
This is a problem w/ the 187.0.0 SDK it should be fixed shortly.
@patflynn @loosebazooka FYI

**Comment by lesv** [comment]
@parindholakia If you wish to roll back to the last SDK you can give the following:

`gcloud components restore` will roll back to the last version.

**Comment by lesv** [comment]
Or `gcloud components update --version 186.0.0` to be very specific.
