### ISSUE TITLE
Gradle does not support the explodeApp or reloadApp tasks

### ISSUE THREAD

**Issue by JohannBlake** [GoogleCloudPlatform/getting-started-java#363]
The documentation at:

[https://cloud.google.com/appengine/docs/standard/java/tools/gradle](https://cloud.google.com/appengine/docs/standard/java/tools/gradle)

indicates that gradle supports the explodeApp and reloadApp tasks. This is not true. The documentation at:

[https://github.com/GoogleCloudPlatform/app-gradle-plugin](https://github.com/GoogleCloudPlatform/app-gradle-plugin)

clearly indicates that these tasks do not exist. Even running those tasks using gradle also indicates that they do not exist. Please remove the documentation referring to these tasks.

**Comment by lesv** [comment]
@GoogleCloudPlatform/cloud-tools-for-java FYI

**Comment by loosebazooka** [comment]
Yes, this appears to be a problem from the docs, I will update them to reflect it is actually `explodeWar`. `reloadApp` however is a custom task written in the docs that users had the option of adding into their build file.

**Comment by dzlier-gcp** [comment]
Duplicate of https://github.com/GoogleCloudPlatform/getting-started-java/issues/369
