### ISSUE TITLE
reloadApp not needed

### ISSUE THREAD

**Issue by JohannBlake** [GoogleCloudPlatform/getting-started-java#369]
In your documentation located at:
[https://cloud.google.com/appengine/docs/standard/java/tools/gradle](https://cloud.google.com/appengine/docs/standard/java/tools/gradle)

it states:

> While your application is running, run explodeApp or reloadApp to reflect your changes into the running application.

You don't need to use the reloadApp task because when the scanning featured is enabled with:

> jvmFlags = ["-Dappengine.fullscan.seconds=5"]

your code changes are automatically loaded. I tried this out. I never use reloadApp and yet it is obvious while the Dev App Server is running that it detects changes. Maybe you should remove the text about reloadApp.

**Comment by lesv** [comment]
@GoogleCloudPlatform/cloud-tools-for-java PTAL / Comments?

**Comment by loosebazooka** [comment]
It looks like this is gone from the documentation. I can't find it anymore. I think we can close this.
