### ISSUE TITLE
Move DaoFilter to use CDI or Factory pattern instead

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/getting-started-java#37]
DAOs should not be produced and stored in request scope. Servlets should use a Factory and/or use CDI to inject the DAO based on configuration.

**Comment by lesv** [comment]
Ray - I suggested Guice originally, but meant Dagger.  Is there something else you would recommend?

**Comment by lesv** [comment]
This was done.  PTAL if you wish.

**Comment by saturnism** [comment]
thnx! lgtm.
