### ISSUE TITLE
HTTP ERROR: 404

### ISSUE THREAD

**Issue by nyembn** [GoogleCloudPlatform/getting-started-java#406]
When trying to run the "4-auth" version locally using "mvn -Plocal clean appengine:devserver -Dbookshelf.bucket=[YOUR-BUCKET]" error 404 comes with no explanation.
HTTP ERROR: 404
Problem accessing /. Reason:

    NOT_FOUND

Powered by Jetty://

**Comment by dzlier-gcp** [comment]
We're rewriting the bookshelf apps now, which should be published in the next month.
