### ISSUE TITLE
Javalin example

### ISSUE THREAD

**Issue by amohabir** [GoogleCloudPlatform/getting-started-java#421]
The latest version of Javalin has the Javalin Servlet exposed, which means it should be able to use it in App Engine. I have an example available in a repo based on the SparkJava example. I would like to contribute that one.

https://github.com/amohabir/javalin-appengine-standard

**Comment by dzlier-gcp** [comment]
Thanks for working on this. Please see the [contribution guide](https://github.com/GoogleCloudPlatform/getting-started-java/blob/master/CONTRIBUTING.md) for how to contribute code to GoogleCloudPlatform repositories.
