### ISSUE TITLE
Flexible sample contains undocumented configuration

### ISSUE THREAD

**Issue by nealeu** [GoogleCloudPlatform/getting-started-java#426]
I'm trying to get my own application deploying to App Engine Flexible, and it seems that the following parameter is to do with the old version.

https://github.com/GoogleCloudPlatform/getting-started-java/blob/c43753ee3bc7a50bdeb3d6af84d215ee59c996ef/flexible/tomcat/helloworld/src/main/appengine/app.yaml#L28

Can you update either our documentation or this sample to ensure that they align so we can see if and why this is needed.

Thanks.

**Comment by averikitsch** [comment]
This sample has been removed
