### ISSUE TITLE
Deprecated method: storage.create

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/getting-started-java#429]
A developer reported that `storage.create` is deprecated and should be changed.

https://github.com/GoogleCloudPlatform/getting-started-java/blob/master/bookshelf/3-binary-data/src/main/java/com/example/getstarted/util/CloudStorageHelper.java#L66

b/110770153

**Comment by dzlier-gcp** [comment]
Bookshelf is being rewritten this quarter, so this will be resolved with that.
