### ISSUE TITLE
com.google.cloud.tools is deprecated

### ISSUE THREAD

**Issue by benkinmat** [GoogleCloudPlatform/getting-started-java#430]
Instead use the old version 
```
<groupId>com.google.cloud.tools</groupId>
<artifactId>appengine-maven-plugin</artifactId>
```
it should be changed to
```
<groupId>com.google.appengine</groupId>
<artifactId>appengine-maven-plugin</artifactId>
```
Follow by: [Failed to execute goal com.google.appengine:appengine-maven-plugin:1.9.67:devserver
](https://stackoverflow.com/questions/53109943/failed-to-execute-goal-com-google-appengineappengine-maven-plugin1-9-67devser)

**Comment by averikitsch** [comment]
Hi @benkinmat, `com.google.cloud.tools.appengine-maven` is currently up to date and `com.google.appengine.appengine-maven` will be deprecated. For more info see, [Migrating to the Cloud SDK](https://cloud.google.com/appengine/docs/standard/java/tools/migrate-maven)
