### ISSUE TITLE
How to add multiple services for bookshelf standard

### ISSUE THREAD

**Issue by Anuradha677** [GoogleCloudPlatform/getting-started-java#435]
Can someone please help me to convert this default services to microservices for bookshelf-standard app engine standard application? I am experimenting on this like each action should be a service, fir example, create books, adding own books, updating books, these are should be different services not in one default service. if I do change some code in creating books, then that service version should be added, not to the default service. I am trying to add app.yaml file in src folder. I am new to GCP. can someone please guide me on this?

app.yaml

runtime: java
api_version: 1
threadsafe: yes
service: book/mine

handlers:
- url: /.*
  script: this field is required, but ignored

**Comment by averikitsch** [comment]
Each of your services would have to be in separate folders to be deployed separately, see [Microservices Architecture on Google App Engine](https://cloud.google.com/appengine/docs/standard/python/microservices-on-app-engine). You're correct that each app.yaml will have the field like: `service: book-service`. This also means setting up communication between your difference services, see [Communicating Between Your Services](https://cloud.google.com/appengine/docs/standard/java/communicating-between-services).
