### ISSUE TITLE
Failed to apply plugin for gradle 5.6

### ISSUE THREAD

**Issue by Anuradha677** [GoogleCloudPlatform/getting-started-java#437]
I am using Gradle 5.6 in the application. When I am trying to build the application I am getting the following error:
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Cloud\appengine-potpourri\endpoints-frontend\build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':endpoints-frontend'.
> Failed to apply plugin [id 'appengine']
   > Could not get unknown property 'classesDir' for functional test classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Reference issue:https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/issues/308
As per this, the issue should not come in the latest version, I am using the latest version of this app engine still I am getting the same issue. Here is 2 build.gradle files.
These 2 build.gradle files reference: https://github.com/patflynn/appengine-potpourri
As this seems to be plugin issue writing over here as the gradle-appengine-plugin repository has been archived.
apply plugin: ‘war’
apply plugin: ‘appengine’

war {
version = ‘1.0’
expand appengineProjectName: appengineProject
}

appengine {
version = ‘1’
project = appengineProject
downloadSdk = true
}

dependencies {
compile ‘javax.servlet:servlet-api:2.5’
compile ‘jstl:jstl:1.2’
compile ‘com.googlecode.objectify:objectify:6.0.4’
compile ‘com.google.endpoints:endpoints-framework:2.2.1’
appengineSdk ‘com.google.appengine:appengine-java-sdk:1.9.76’
}

another build.gradle

buildscript {
repositories {
mavenCentral()
}

dependencies {
    classpath 'com.google.appengine:gradle-appengine-plugin:1.9.59'
}
}

subprojects {
repositories {
mavenCentral()
}

apply plugin: 'java'
sourceCompatibility = '1.8'
targetCompatibility = '1.8'
tasks.withType(JavaCompile) { options.encoding = 'UTF-8' }

dependencies {
}
}

**Comment by lesv** [comment]
@averikitsch Do you look at these?  Could you?

**Comment by averikitsch** [comment]
This looks specific to the App Engine plugins. @elharo can you route this appropriately?

**Comment by elharo** [comment]
Ask @suztomo to take a look but I can't assign him in this repo

**Comment by lesv** [comment]
Obsolete
