### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by nkalra0123** [GoogleCloudPlatform/getting-started-java#505]
It is mentioned in the Readme of this project: https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/springboot-appengine-standard

that -

> You must use WAR packaging to deploy into Google App Engine Standard, 

and it is also suggested to remove tomcat and add SpringBootServletInitializer

But in the codelab : https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html#0

Anything like this is not required, and I have also tried to deploy the sample code(https://github.com/nkalra0123/spring-boot-dump-headers) at App engine, 

And I have checked that my project is scaled down to zero instances when there is no request, which is not possible in Flexible environment

**Comment by lesv** [comment]
Good catch - things have changed since that was written.
