### ISSUE TITLE
Rename region tag "runtime"

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/getting-started-java#655]
The Sample Tracker requires a valid region tag format. A valid region tag looks like `product_my_region_tag`.

The tag `runtime` doesn't have a product. It should probably be `gae_runtime` or some name.

https://github.com/GoogleCloudPlatform/getting-started-java/blob/3ce78bc3c3e8d841f025e21e162d11f274e06b8f/bookshelf/3-binary-data/src/main/appengine/app.yaml#L17

**Comment by lesv** [comment]
Care to explain?

**Comment by grant** [comment]
> Care to explain?

Yes! I updated the poorly defined issue.

The sample tracker pointed this issue out.

**Comment by grant** [comment]
Why was this closed?

**Comment by lesv** [comment]
Users can't see sample tracker.

**Comment by lesv** [comment]
Bookshelf is out of date and not being actively worked on.

@averikitsch FYI
