### ISSUE TITLE
Spring-boot does not deploy

### ISSUE THREAD

**Issue by tomhughesnice** [GoogleCloudPlatform/getting-started-java#84]
Hi,

I have been trying to deploy the sample spring-boot application, but the deployment always fails.
My maven, Java and gcloud cmd line tools are all up to date btw.

From what I can tell from the logs i pulled below it looks like the deploy started. But there are various different errors reported(Highlighted), but Im not sure which are critical.

`May 24 20:46:21 vm_runtime_init: Done start 'nginx_proxy_start'.
May 24 20:46:21 vm_runtime_init: start 'ah_start'.
**May 24 20:46:21 vm_runtime_init: ah_start: ERROR: app container not found running.**
May 24 20:46:21 Aborting!
CONTAINER ID        IMAGE                                                                                                                                   COMMAND                  CREATED             STATUS                                  PORTS                                                      NAMES
3b67c1c89af3        gcr.io/google_appengine/mvm-agent                                                                                                       "/usr/local/bin/gunic"   1 seconds ago       Up 1 seconds                                                                                       mad_mclean
264cb2eac1d0        gcr.io/google_appengine/nginx-proxy                                                                                                     "/var/lib/nginx/bin/s"   2 seconds ago       Up 1 seconds                            0.0.0.0:8080->8080/tcp, 0.0.0.0:8443->8443/tcp, 8090/tcp   angry_newton
f9ac2bbfb366        us.gcr.io/helloworld-spring/appengine/default.20160524t214203@sha256:ca22eb4b3d31c0fbcb3356fdc9405dc1c9a2fad34098b1dbc52cb142f3bbdf9e   "java -jar /app/hello"   4 seconds ago       Restarting (1) Less than a second ago                                                              gaeapp
a6c850958848        gcr.io/google_appengine/memcache-proxy                                                                                                  "/home/memcache/memca"   5 seconds ago       Up 4 seconds                            11211/tcp                                                  memcache
e5e148c56e87        gcr.io/google_appengine/api-verifier                                                                                                    "./api_verifier.py"      7 seconds ago       Exited (0) 6 seconds ago                                                                           agitated_heisenberg
44dbc07aba41        gcr.io/google_appengine/fluentd-logger                                                                                                  "/opt/google-fluentd/"   12 seconds ago      Up 11 seconds                                                                                      hungry_pike
Container: 3b67c1c89af3
[2016-05-24 20:46:22 +0000] [1] [INFO] Starting gunicorn 19.2.1
[2016-05-24 20:46:22 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2016-05-24 20:46:22 +0000] [1] [INFO] Using worker: gevent
[2016-05-24 20:46:22 +0000] [9] [INFO] Booting worker with pid: 9
Container: 264cb2eac1d0
Generating RSA private key, 2048 bit long modulus
........................+++
...............................................+++
e is 65537 (0x10001)
Signature ok
subject=
Getting Private key
Restarting periodic command scheduler: cronStopping periodic command scheduler: cron.
Starting periodic command scheduler: cron.
Container: f9ac2bbfb366
**no main manifest attribute, in /app/helloworld-springboot-0.0.1-SNAPSHOT.jar
no main manifest attribute, in /app/helloworld-springboot-0.0.1-SNAPSHOT.jar
no main manifest attribute, in /app/helloworld-springboot-0.0.1-SNAPSHOT.jar
no main manifest attribute, in /app/helloworld-springboot-0.0.1-SNAPSHOT.jar**
Container: a6c850958848
Container: e5e148c56e87
**No handlers could be found for logger "google.appengine.ext.vmruntime.vmstub"**
number of instances:  1
Container: 44dbc07aba41
========= rebooting. ========================

INIT: 
INIT: Sending processes the TERM signal

INIT: Sending processes the KILL signal

`

If I could get some help that would be appreciated.

**Comment by lesv** [comment]
Thanks.

I've asked the author to take a look.
